name: dca_portfolio_nbr
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11  # Specify your Python version here
  - numpy
  - pandas
  - matplotlib
  - ipywidgets
  - notebook  # This includes Jupyter Notebook
  - pip
  - pip:
    - financetoolkit  # Assuming financetoolkit is a PyPI package and not available in Conda channels

